### ISSUE TITLE
Segfault during VerifyUserSignature

### ISSUE THREAD

**Issue by devinivy** [bluesky-social/indigo#37]
I run into this segfault consistently when pointing bigsky at the PDS dev environment setup.  I am running bigsky on https://github.com/bluesky-social/indigo/commit/9a357fe32a01f706a96aaa7324f92978c4a235a4 with the following command:
```
./bigsky --aggregation=false --ssl-events=false --plc-host="http://localhost:2582"
``` 

Output:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x100220d86]

goroutine 63 [running]:
math/big.(*Int).Sign(...)
        /usr/local/go/src/math/big/int.go:41
crypto/ecdsa.(*nistCurve[...]).pointFromAffine(0x100f86be0, 0x0, 0x0)
        /usr/local/go/src/crypto/ecdsa/ecdsa.go:575 +0x46
crypto/ecdsa.verifyNISTEC[...](0xc00061ee40, 0xc000333568, {0xc000333508, 0x20, 0x20}, {0xc000616600, 0x0?, 0x0?})
        /usr/local/go/src/crypto/ecdsa/ecdsa.go:494 +0xc5
crypto/ecdsa.VerifyASN1(0xc000333568, {0xc000333508, 0x20, 0x20}, {0xc000616600, 0x48, 0x60})
        /usr/local/go/src/crypto/ecdsa/ecdsa.go:478 +0x285
crypto/ecdsa.Verify(0x11000371f53b00?, {0xc000333508, 0x20, 0x20}, 0xc0007366f0?, 0xc00033a7c0)
        /usr/local/go/src/crypto/ecdsa/ecdsa_legacy.go:126 +0x10b
github.com/whyrusleeping/go-did.(*PubKey).Verify(0xc00033a780, {0xc0007366f0, 0x24, 0x30}, {0xc000618380, 0x40, 0x40})
        /Users/devinivy/go/pkg/mod/github.com/whyrusleeping/go-did@v0.0.0-20230217165439-d09707c62f1c/key.go:158 +0x2f9
github.com/bluesky-social/indigo/indexer.(*KeyManager).VerifyUserSignature(0xc0006125f0?, {0x100f89d60, 0xc00061b020}, {0xc00062a3c0, 0x20}, {0xc000618380, 0x40, 0x40}, {0xc0007366f0, 0x24, ...})
        /project/indigo/indexer/keymgr.go:37 +0x185
github.com/bluesky-social/indigo/repomgr.(*RepoManager).HandleExternalUserEvent(0xc00071ffc0, {0x100f89cf0, 0xc000120008}, 0x1, 0x1, {0xc00071c7a0, 0x20}, 0x0, {0xc0005ee000, 0x2b3, ...})
        /project/indigo/repomgr/repomgr.go:548 +0x4ec
github.com/bluesky-social/indigo/bgs.(*BGS).handleFedEvent(0xc0002bf4f0, {0x100f89cf0, 0xc000120008}, 0xc000308090, 0xc0005ee001?)
        /project/indigo/bgs/bgs.go:269 +0x434
github.com/bluesky-social/indigo/bgs.(*Slurper).handleConnection.func1(0xc0005d8300)
        /project/indigo/bgs/fedmgr.go:139 +0x1a7
github.com/bluesky-social/indigo/events.HandleRepoStream({0x100f89cb8?, 0xc0005c2a50?}, 0xc000455e40, 0xc000333df0)
        /project/indigo/events/consumer.go:63 +0x213
github.com/bluesky-social/indigo/bgs.(*Slurper).handleConnection(0xc000300990, 0xc000308090, 0x0?, 0xc000323ea8)
        /project/indigo/bgs/fedmgr.go:135 +0x117
github.com/bluesky-social/indigo/bgs.(*Slurper).subscribeWithRedialer(0xc000300990, 0xc000308090)
        /project/indigo/bgs/fedmgr.go:105 +0x370
created by github.com/bluesky-social/indigo/bgs.(*Slurper).SubscribeToPds
        /project/indigo/bgs/fedmgr.go:70 +0x378
```

**Comment by whyrusleeping** [comment]
this ones a head scratcher... the key in question (according to the stack trace) is fine?

**Comment by bnewbold** [comment]
Oh golly do I not like to see `VerifyASN1` in a stack trace.

@devinivy what platform are you encountering this on? Apple silicon (M1, M2)? Don't have a specific hypothesis but could help track this down.

**Comment by devinivy** [comment]
@bnewbold yup that's right, it's Apple silicon.  Actually I think we had some good news here— @whyrusleeping made a fix in go-did that I pulled down locally and it resolved the issue.  I am not sure if that fix made its way into bgs yet, though.  Here's the commit: https://github.com/whyrusleeping/go-did/commit/2146016fc220aa1e08ccf26aaa762f5a11a81404

**Comment by bnewbold** [comment]
I think we fixed this in https://github.com/bluesky-social/indigo/pull/42
